language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - npm i -g @angular/cli
  - npm i
deploy_beta:
  - provider: script
    script: ng build -c beta && s3-deploy './dist/gatool-ui/*' --cwd './dist/gatool-ui' --region us-east-1 --bucket beta.gatool.org --distId E2G6T2LTLBO3Q
    on:
      branch: beta
deploy_prod:
  - provider: script
    script: ng build -c production && npm run deploy-production
    on:
      branch: master
