import moment from "moment";
import { buildWeek0PracticeTraining } from "../data/week0PracticeTraining";

const today = moment().format("YYYY-MM-DD");

const {
  trainingSchedule,
  trainingScores,
  trainingRanks,
  trainingTeams,
  trainingAlliances,
} = buildWeek0PracticeTraining(today);

const trainingEvents = {};
trainingEvents.events = [
  {
    allianceCount: "EightAlliance",
    weekNumber: 0,
    announcements: [],
    code: "PRACTICE1",
    divisionCode: null,
    name: "Practice Event Phase 1",
    type: "OffSeasonWithAzureSync",
    districtCode: null,
    venue: "Bishop Guertin High School",
    city: "Nashua",
    stateprov: "NH",
    country: "USA",
    dateStart: moment().format(),
    dateEnd: moment().format(),
    address: "194 Lund Rd",
    website: "N/A",
    webcasts: [
      "https://www.twitch.tv/firstinspires",
      "https://www.twitch.tv/firstinspires1",
    ],
    timezone: "Eastern Standard Time",
  },
  {
    allianceCount: "EightAlliance",
    weekNumber: 0,
    announcements: [],
    code: "PRACTICE2",
    divisionCode: null,
    name: "Practice Event Phase 2",
    type: "OffSeasonWithAzureSync",
    districtCode: null,
    venue: "Bishop Guertin High School",
    city: "Nashua",
    stateprov: "NH",
    country: "USA",
    dateStart: moment().format(),
    dateEnd: moment().format(),
    address: "194 Lund Rd",
    website: "N/A",
    webcasts: [
      "https://www.twitch.tv/firstinspires",
      "https://www.twitch.tv/firstinspires1",
    ],
    timezone: "Eastern Standard Time",
  },
  {
    allianceCount: "EightAlliance",
    weekNumber: 0,
    announcements: [],
    code: "PRACTICE3",
    divisionCode: null,
    name: "Practice Event Phase 3",
    type: "OffSeasonWithAzureSync",
    districtCode: null,
    venue: "Bishop Guertin High School",
    city: "Nashua",
    stateprov: "NH",
    country: "USA",
    dateStart: moment().format(),
    dateEnd: moment().format(),
    address: "194 Lund Rd",
    website: "N/A",
    webcasts: [
      "https://www.twitch.tv/firstinspires",
      "https://www.twitch.tv/firstinspires1",
    ],
    timezone: "Eastern Standard Time",
  },
  {
    allianceCount: "EightAlliance",
    weekNumber: 0,
    announcements: [],
    code: "PRACTICE4",
    divisionCode: null,
    name: "Practice Event Phase 4",
    type: "OffSeasonWithAzureSync",
    districtCode: null,
    venue: "Bishop Guertin High School",
    city: "Nashua",
    stateprov: "NH",
    country: "USA",
    dateStart: moment().format(),
    dateEnd: moment().format(),
    address: "194 Lund Rd",
    website: "N/A",
    webcasts: [
      "https://www.twitch.tv/firstinspires",
      "https://www.twitch.tv/firstinspires1",
    ],
    timezone: "Eastern Standard Time",
  },
  {
    allianceCount: "EightAlliance",
    weekNumber: 0,
    announcements: [],
    code: "OFFLINE",
    divisionCode: null,
    name: "OFFLINE",
    type: "OffSeasonWithAzureSync",
    districtCode: null,
    venue: "OFFLINE",
    city: "City",
    stateprov: "State",
    country: "Country",
    dateStart: moment().format(),
    dateEnd: moment().format(),
    address: "Street",
    website: "N/A",
    webcasts: [
      "https://www.twitch.tv/firstinspires",
      "https://www.twitch.tv/firstinspires1",
    ],
    timezone: "Eastern Standard Time",
  },
];

export const trainingData = {
  events: trainingEvents,
  alliances: trainingAlliances,
  ranks: trainingRanks,
  teams: trainingTeams,
  schedule: trainingSchedule,
  scores: trainingScores,
};
