/**
 * Absolute path under the app root for a file in `public/` (respects `homepage` / PUBLIC_URL).
 */
export function getPublicUrl(path) {
  const normalized = path.startsWith("/") ? path : `/${path}`;
  const base = (process.env.PUBLIC_URL || "").replace(/\/$/, "");
  return `${base}${normalized}`;
}

/**
 * Static help bundle (generated by `npm run sync-help-docs`, run on `npm run build` / `prestart`).
 * Commit `public/help-docs.html` to ship a wiki snapshot without live fetches.
 */
export function getHelpDocsUrl() {
  return getPublicUrl("/help-docs.html");
}

/** Manifest listing wiki pages + raw GitHub URLs (written by sync-help-docs). */
export function getHelpWikiManifestUrl() {
  return getPublicUrl("/help-wiki-manifest.json");
}

/** When true, Help loads markdown from GitHub raw wiki URLs using the manifest (needs network). */
export function useHelpLiveWiki() {
  return process.env.REACT_APP_HELP_LIVE_WIKI === "true";
}
