/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
// @ts-ignore
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith('/_')) {
      return false;
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.

    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// Cache all public folder assets with CacheFirst strategy for offline support
// This includes PDFs, images, SVGs, and other static resources
registerRoute(
  ({ url }) => {
    return url.origin === self.location.origin && (
      url.pathname.startsWith('/images/') ||
      url.pathname.startsWith('/cheatsheet/') ||
      url.pathname.startsWith('/bracket/') ||
      url.pathname.startsWith('/json/') ||
      url.pathname.endsWith('.pdf') ||
      url.pathname.endsWith('.png') ||
      url.pathname.endsWith('.jpg') ||
      url.pathname.endsWith('.jpeg') ||
      url.pathname.endsWith('.gif') ||
      url.pathname.endsWith('.svg') ||
      url.pathname.endsWith('.docx') ||
      url.pathname.endsWith('.doc')
    );
  },
  new CacheFirst({
    cacheName: 'public-assets',
    plugins: [
      // Cache for 30 days
      new ExpirationPlugin({ 
        maxAgeSeconds: 30 * 24 * 60 * 60,
        maxEntries: 500, // Limit cache to 500 assets
      }),
    ],
  })
);

// Cache external fonts from Adobe Typekit, Google Fonts, and other CDNs
registerRoute(
  ({ url }) => {
    return (
      // Adobe Typekit/Adobe Fonts
      url.origin === 'https://use.typekit.net' ||
      url.origin === 'https://p.typekit.net' ||
      // Google Fonts
      url.origin === 'https://fonts.googleapis.com' ||
      url.origin === 'https://fonts.gstatic.com' ||
      // Font file extensions from any origin
      url.pathname.endsWith('.woff') ||
      url.pathname.endsWith('.woff2') ||
      url.pathname.endsWith('.ttf') ||
      url.pathname.endsWith('.otf') ||
      url.pathname.endsWith('.eot')
    );
  },
  new CacheFirst({
    cacheName: 'external-fonts',
    plugins: [
      // Cache fonts for 1 year - they rarely change
      new ExpirationPlugin({ 
        maxAgeSeconds: 365 * 24 * 60 * 60,
        maxEntries: 100,
      }),
    ],
  })
);

// Cache HTML files and other same-origin content with StaleWhileRevalidate
registerRoute(
  ({ url }) => url.origin === self.location.origin,
  new StaleWhileRevalidate({
    cacheName: 'public-files',
    plugins: [
      // Expire cached objects after 5 days
      new ExpirationPlugin({ maxAgeSeconds: 432000, }),
    ],
  })
);

// Cache the most recent 200 avatar PNGs
registerRoute(
  ({ url }) => url.pathname.endsWith('avatar.png'),
  new StaleWhileRevalidate({
    cacheName: 'avatars',
    plugins: [
      new ExpirationPlugin({ maxEntries: 200 }),
    ],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    // @ts-ignore
    self.skipWaiting();
  }
});

// Any other custom service worker logic can go here.
